# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off


# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'vaaleyard/tmux-dotbar'

# tmux-sensible

## Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

## Increase scrollback buffer size from 2000 to 10000 lines
set -g history-limit 10000

## Refresh 'status-left' and 'status-right' more often, from every 17s to 5s
set -g status-interval 5

set -g @tmux-dotbar-bg "#000000"
set -g @tmux-dotbar-fg-current "#cdd6f4"
set -g @tmux-dotbar-fg-session "#9399b2"
set -g @tmux-dotbar-bg-prefix "#cba6f7"

set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-right-text '#[bg=terminal fg=green]#[bg=green fg=black]%Y-%m-%d %H:%M#[bg=terminal fg=green]#[bg=green fg=black]'

# Messages theme
set -g message-style 'fg=black bg=cyan bold'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
